# Generated by Django 6.1 on 2026-08-29 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("work_mode", models.CharField(blank=True, max_length=50)),
                ("experience_level", models.CharField(blank=True, max_length=100)),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("url", models.URLField(blank=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("risk_score", models.CharField(default="LOW RISK", max_length=20)),
                ("risk_reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Saved", max_length=50)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidateprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
    ]
